using OutlookWidget.Core.Caching;
using OutlookWidget.Core.Diagnostics;
using OutlookWidget.Core.Refresh;

namespace OutlookWidget.Core.Delivery;

/// <summary>
/// The single serialized delivery worker: one pass at a time, requests coalesced to a
/// pending marker of depth one, and committed state re-read at the start of every pass.
/// </summary>
/// <remarks>
/// <para>
/// <b>The problem this solves.</b> Moving delivery out of the refresh lease removes a
/// timing problem — an unbounded host call can no longer outlive the lease horizon — but
/// creates an ordering one. With no lease held, two callers could invoke
/// <c>UpdateWidget</c> concurrently, and a slow older call can land after a newer refresh,
/// logout, account switch, or privacy commit. Whatever reaches the host last becomes the
/// displayed content, and the cache generation cannot help: it guards the cache, and a
/// payload already handed to the host cannot be retracted. Ordering must therefore be
/// established before the call, not validated after it.
/// </para>
/// <para>
/// <b>How.</b> One worker means no two host calls are ever in flight, so there is no
/// interleaving to order. The trigger carries no payload: each pass performs a fresh read
/// of the snapshot, its generation, and the tombstone, and builds content from
/// <em>that</em>. A request generated by an old refresh cannot carry stale content forward,
/// because the content is chosen at delivery time rather than at request time.
/// </para>
/// <para>
/// <b>What this guarantees, and what it does not.</b> Concurrent requests collapse into a
/// single pending flag, and a request arriving mid-pass causes exactly one more pass
/// afterwards, so the <em>final</em> rendered content always reflects the newest committed
/// state. This is final convergence, not retraction. Once a payload has entered
/// <see cref="IWidgetDeliverySink.Deliver"/>, no later tombstone, generation change, or
/// logout can alter or recall it. If a pass had already read state and entered the call
/// when a disclosure-reducing change commits, that older payload can still land — and with
/// a wedged host it can land noticeably later, briefly showing pre-change content before
/// the follow-up pass replaces it. The window is narrow by construction, because state is
/// re-read immediately before the call rather than captured earlier, but it is not zero and
/// this type does not pretend otherwise.
/// </para>
/// </remarks>
public sealed class DeliveryWorker : IDisposable
{
    private readonly ProtectedCache _cache;
    private readonly DisclosureTombstoneStore _tombstones;
    private readonly IWidgetDeliverySink _sink;
    private readonly IOperationalLogger _logger;

    private readonly Lock _gate = new();
    private readonly SemaphoreSlim _work = new(0, 1);
    private readonly CancellationTokenSource _shutdown = new();
    private readonly Thread _worker;

    /// <summary>
    /// The coalescing pending marker. Depth one: additional requests while one is already
    /// pending change nothing, which is the point — the pass reads current state, so N
    /// queued requests and one queued request produce identical output.
    /// </summary>
    private bool _pending;

    private bool _passInProgress;
    private long _completedPasses;
    private long _coalescedRequests;
    private bool _disposed;

    public DeliveryWorker(
        ProtectedCache cache,
        DisclosureTombstoneStore tombstones,
        IWidgetDeliverySink sink,
        IOperationalLogger? logger = null)
    {
        ArgumentNullException.ThrowIfNull(cache);
        ArgumentNullException.ThrowIfNull(tombstones);
        ArgumentNullException.ThrowIfNull(sink);

        _cache = cache;
        _tombstones = tombstones;
        _sink = sink;
        _logger = logger ?? NullOperationalLogger.Instance;

        // A dedicated foreground-less thread rather than the thread pool. The sink can
        // block indefinitely in a wedged host, and parking a pool thread there would
        // starve unrelated work — including the refresh path this must never block.
        _worker = new Thread(RunLoop)
        {
            IsBackground = true,
            Name = "OutlookWidget.Delivery",
        };
        _worker.Start();
    }

    /// <summary>How many delivery passes have completed. For assertions and diagnostics.</summary>
    public long CompletedPasses => Interlocked.Read(ref _completedPasses);

    /// <summary>
    /// How many requests were absorbed by an already-pending marker rather than causing
    /// their own pass. A direct measure of coalescing.
    /// </summary>
    public long CoalescedRequests => Interlocked.Read(ref _coalescedRequests);

    /// <summary>
    /// Requests a delivery pass. Returns immediately: this is a marker, not a call.
    /// </summary>
    /// <remarks>
    /// Safe to call from anywhere in the provider process, including the refresh path, an
    /// <c>Activate</c> callback, and the state-changed event listener. None of them block
    /// on the host, and none of them supply content.
    /// </remarks>
    public void RequestDelivery()
    {
        if (_disposed)
        {
            return;
        }

        bool release = false;

        lock (_gate)
        {
            if (_pending)
            {
                // Already pending. Nothing to add: the pass will read current state.
                Interlocked.Increment(ref _coalescedRequests);
                _logger.Record(OperationalEventId.DeliveryCoalesced, OperationalOutcome.Skipped);
                return;
            }

            _pending = true;

            // If a pass is running, do not signal. The running pass observes the marker
            // when it finishes and runs exactly one more time. Signalling here as well
            // would let the semaphore accumulate a second permit and produce a redundant
            // empty pass.
            if (!_passInProgress)
            {
                release = true;
            }
            else
            {
                Interlocked.Increment(ref _coalescedRequests);
                _logger.Record(OperationalEventId.DeliveryCoalesced, OperationalOutcome.Skipped);
            }
        }

        _logger.Record(OperationalEventId.DeliveryRequested, OperationalOutcome.Success);

        if (release)
        {
            _work.Release();
        }
    }

    private void RunLoop()
    {
        while (!_shutdown.IsCancellationRequested)
        {
            try
            {
                _work.Wait(_shutdown.Token);
            }
            catch (OperationCanceledException)
            {
                return;
            }

            // Drain the marker and run passes until nothing is pending. The inner loop is
            // what makes a request arriving mid-pass produce exactly one follow-up pass
            // rather than depending on a second semaphore permit.
            while (true)
            {
                lock (_gate)
                {
                    if (!_pending)
                    {
                        _passInProgress = false;
                        break;
                    }

                    _pending = false;
                    _passInProgress = true;
                }

                RunOnePass();
            }
        }
    }

    private void RunOnePass()
    {
        // Re-read everything. This is the ordering guarantee: content is chosen now, not
        // when the request was made. The tombstone is read alongside the snapshot so a
        // pass that has not yet entered the host call honours the current suppression.
        DisclosureMode mode = _tombstones.GetEffectiveMode();
        CacheReadResult read = _cache.Read();

        var state = new DeliveryState(
            read.Generation,
            mode,
            read.Status,
            // Withhold the payload entirely when suppressed to signed-out. The sink cannot
            // leak what it was never given, which is a stronger guarantee than trusting
            // every future render path to check the mode.
            mode == DisclosureMode.SignedOut ? null : read.Payload);

        try
        {
            _sink.Deliver(state);

            Interlocked.Increment(ref _completedPasses);
            _logger.Record(OperationalEventId.DeliveryCompleted, OperationalOutcome.Success);
        }
        catch (Exception e) when (e is not OperationCanceledException)
        {
            // A wedged or failing Widgets host is a host-level failure the provider cannot
            // fix. It must not corrupt refresh accounting, leave a lease outstanding, or
            // block the next activation — so it is recorded and the loop continues.
            Interlocked.Increment(ref _completedPasses);
            _logger.Record(OperationalEventId.DeliveryFailed, OperationalOutcome.Failed);
        }
    }

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        _shutdown.Cancel();

        // Do not join indefinitely. The worker may be parked inside a wedged host call,
        // and blocking provider shutdown on that would turn a rendering problem into a
        // process that will not exit — the provider must exit cleanly after the last
        // enabled widget is deleted.
        _worker.Join(TimeSpan.FromSeconds(2));

        _shutdown.Dispose();
        _work.Dispose();
    }
}
